### ISSUE TITLE
TODO: joke article about saving energy if we don't communicate

### ISSUE THREAD

**Issue by Naereen** [Naereen/me#13]
- [ ] See who wants to help
- [ ] Start a template on OverLeaf
- [ ] Find some references
- [ ] Do some "dummy" graphs
- [ ] Release the simulation code
- [ ] Write 3-5 pages in single column
- [ ] Maybe send it to URSI ?
- [ ] At least publish it on HAL and open everything
- [ ] … of course, explicitely say that it's a joke!
