### ISSUE TITLE
TODO Article on expert aggregation for Multi-Player MAB model for Internet of Things

### ISSUE THREAD

**Issue by Naereen** [Naereen/me#14]
> Seul ! Juste modèle + algorithmes + simulations, pas de théorie.

- [ ] finir les simulations
- [ ] relire tout et compresser introduction => pour des courbes plus grandes (ou sans légendes ?). :warning: 4 pages maximum !
- [ ] aux news quand on l'envoie
- [ ] avec lien vers PDF dès que prêt
- [ ] avec lien vers article HAL dès que disponible
- [ ] aux publis dès qu'il est accepté
- [ ] avec DOI ?

**Comment by Naereen** [comment]
> Je bosserai sur ça vendredi après-midi et ce weekend, ce sera fini lundi matin.
