### ISSUE TITLE
TODO Article "Doubling Tricks"

### ISSUE THREAD

**Issue by Naereen** [Naereen/me#6]
- [ ] aux news quand on l'envoie
- [x] avec lien vers PDF dès que prêt
- [x] avec version web Engrafo : https://perso.crans.org/besson/articles/BK__ALT_2019/
- [x] avec liens vers les sources LaTeX dès que possible, http://bitbucket.org/lbesson/what-doubling-tricks-can-and-cant-do-for-multi-armed-bandits
- [x] avec lien vers article HAL & arXiv dès que disponible, https://hal.inria.fr/hal-01736357 & https://arxiv.org/abs/1803.06971
- [ ] aux publis dès qu'il est accepté
- [ ] lien vers les slides dès que le talk est donné (voir https://github.com/Naereen/slides/issues/10)
- [ ] avec DOI ?
