### ISSUE TITLE
TODO: article on sparse bandits and structured bandits

### ISSUE THREAD

**Issue by Naereen** [Naereen/me#8]
- [ ] avec lien vers PDF dès que prêt
- [ ] aux news quand on l'envoie
- [ ] avec lien vers article HAL & arXiv dès que disponible
- [ ] avec version web Engrafo ?
- [ ] aux publis dès qu'il est accepté
- [ ] avec lien vers les planches dès que possible
- [ ] avec DOI ?
